### ISSUE TITLE
How to build one using windows?

### ISSUE THREAD

**Issue by Maxhem2** [alvin-tosh/Kenyatta-Ransomware#2]
The title

**Comment by alvin-tosh** [comment]
The Title?

**Comment by Maxhem2** [comment]
How can I build this on a windows system, I dont have linux and on my linux ubuntu vm had massive problems, starting with the clone command linking to a non existent repo

**Comment by alvin-tosh** [comment]
right right
have you tried the Linux distro that comes with win11....Windows though i think it is posible its just too complicated...

**Comment by Maxhem2** [comment]
I have also tried on my linux vm which didnt work with the provided guide, a video tutorial would be helpfull

**Comment by alvin-tosh** [comment]
alright
